name = "OrchardGame"
uuid = "dbd6f42d-9bd3-4812-b087-95797f78d24c"
authors = ["Hannes Becher"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
